---
# K3s Configuration
k3s_cluster_domain: "cluster.local"
k3s_service_cidr: "10.43.0.0/16"
k3s_cluster_cidr: "10.42.0.0/16"
k3s_cluster_dns: "10.43.0.10"

# K3s Server Arguments
k3s_server_args:
  - "--disable=traefik"
  - "--disable=servicelb"
  - "--write-kubeconfig-mode=644"
  - "--etcd-expose-metrics=true"
  - "--kube-controller-manager-arg=bind-address=0.0.0.0"
  - "--kube-scheduler-arg=bind-address=0.0.0.0"
  - "--kube-proxy-arg=metrics-bind-address=0.0.0.0"

# K3s Agent Arguments
k3s_agent_args:
  - "--node-label=node-role.kubernetes.io/worker=true"

# Container Registry
registry_url: "registry.{{ domain_name }}"
registry_username: "admin"
registry_password: "{{ vault_registry_password }}"
