---
- name: Restart ntp
  ansible.builtin.systemd:
    name: ntp
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
