---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - vim
      - git
      - htop
      - net-tools
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
      - ufw
      - fail2ban
      - unattended-upgrades
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Configure NTP
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: '0644'
  notify: restart ntp

- name: Enable and start NTP service
  ansible.builtin.systemd:
    name: ntp
    enabled: true
    state: started

- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'vm.max_map_count', value: '262144' }
    - { key: 'fs.file-max', value: '131072' }

- name: Load kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Persist kernel modules
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
    mode: '0644'
  loop:
    - br_netfilter
    - overlay

- name: Configure firewall rules
  ansible.builtin.include_tasks: firewall.yml
