---
- name: Restart prometheus
  community.docker.docker_container:
    name: prometheus
    restart: true

- name: Restart grafana
  community.docker.docker_container:
    name: grafana
    restart: true

- name: Restart loki
  community.docker.docker_container:
    name: loki
    restart: true

- name: Restart alertmanager
  community.docker.docker_container:
    name: alertmanager
    restart: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
