---
- name: Security Hardening
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Apply security role
      ansible.builtin.include_role:
        name: security
      tags: security

- name: Additional security hardening
  hosts: k3s_cluster
  gather_facts: false
  become: true

  tasks:
    - name: Disable unused kernel modules
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/blacklist-rare-network.conf
        line: "blacklist {{ item }}"
        create: true
        mode: '0644'
      loop:
        - dccp
        - sctp
        - rds
        - tipc

    - name: Set kernel parameters for security
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop:
        - { name: 'kernel.dmesg_restrict', value: '1' }
        - { name: 'kernel.kptr_restrict', value: '2' }
        - { name: 'kernel.yama.ptrace_scope', value: '1' }
        - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
        - { name: 'net.ipv4.conf.default.log_martians', value: '1' }
        - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }

    - name: Configure auditd
      ansible.builtin.package:
        name: auditd
        state: present

    - name: Start and enable auditd
      ansible.builtin.systemd:
        name: auditd
        state: started
        enabled: true

    - name: Configure log rotation
      ansible.builtin.template:
        src: logrotate-k3s.j2
        dest: /etc/logrotate.d/k3s
        mode: '0644'
